{
    'name': 'Sparrow SMS API',
    'version': '1.0',
 #   'summary': '',
    'description': 'Send bulk SMS through Odoo',
 #  'category': '',
    'author': 'BI Solutions',
    'website': 'bisolutions.asia',
    # 'license': 'BI Solutions',
    'depends': ['contacts'],
    'data': ['sms_menu.xml','sms_view.xml'],
    'application': 'True',
    # 'demo': [''],
    'installable': True,
    'auto_install': False,
}
